# Generated by Django 2.1.2 on 2019-05-21 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='type_addresses',
        ),
        migrations.RemoveField(
            model_name='pizzeria',
            name='type_address',
        ),
        migrations.AddField(
            model_name='pizzeria',
            name='address',
            field=models.ForeignKey(default='', help_text='The address for this pizzeria.', on_delete=django.db.models.deletion.CASCADE, to='pizzapp.Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeaddress',
            name='customer',
            field=models.ForeignKey(default='', help_text='The customer for this type address.', on_delete=django.db.models.deletion.PROTECT, to='pizzapp.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='password',
            field=models.CharField(help_text='The user password.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type_address',
            field=models.ForeignKey(help_text='The address for this supplier.', null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzapp.Address'),
        ),
    ]
